---
title: "Mean annual rainfall"
author: "LBE"
date: "2024-04-11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
library(janitor)
library (lubridate)
```

## Sam's data wrangling

```{r rain}
hr <- read_xls("data/Hazelrigg Rainfall 1966-.xls",
               range = "year!A1:BI367",
               col_types = c("numeric", "numeric", rep("text", 59))
) |>
  pivot_longer("1966":"2024", names_to = "year", values_to = "rainfall_mm") |>
  mutate(rainfall_mm = rainfall_mm |>
           #replace Trace|trace|tr|Tr with 0.01
           str_replace_all("[Tt]{1}.*\\b", "0.01") |>
           #replace anything starting with "a point"." with "0."
           # some ambiguity because could be that ".0" was typed instead of "0."
           str_replace_all("^\\.(.*)", "0.\\1") |>
           #remove trailing point symbol
           str_replace_all("(.*)\\.$", "\\1") |>
           #convert to numeric and round to 2 dp
           as.numeric() #|> round(digits = 2)
  ) |>
  arrange(year, Month, Date) |>
  clean_names()

```

## Lisa's data wrangling

```{r}
hr_annual <- hr %>% 
   mutate(t = str_c(month, date, sep = "_")) %>% 
    filter(!is.na(rainfall_mm)) %>% #remove 1966 Na's
    mutate(month = month(month, label = TRUE))

hr_monthly <- hr_annual %>% 
   group_by(year, month) %>% 
   summarise(monthly_rain = mean(rainfall_mm))

hr_overall = hr_monthly %>% 
   group_by(month) %>% 
   summarise(rain = mean(monthly_rain))
```


1. First make it a function, with a single year highlighted
```{r}

highlight_month <- function(yr = 1982){
ggplot() +
   geom_line(data = hr_monthly, aes(x = month, y = monthly_rain, group = year),
             show.legend = F, 
             colour = "grey", 
             alpha = 0.7,
             linewidth = 1.1) +
    geom_line(data = hr_overall, aes(x=month, y = rain, group = 1), 
              colour = "grey40",
              linewidth = 1.2)+
    geom_line(data = subset(hr_monthly, year == yr), 
              aes(x = month, y = monthly_rain, colour = year, group = 1))+
    labs(y = "Average rain (mm)", x = "Month")+
   theme_classic()
}

highlight_month(yr = 1995)
```

2. now try to include multiple years?

```{r}

```

