---
title: "hazelrigg_cleaning"
author: "Samuel Taylor"
date: "2024-04-04"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
library(janitor)
```

## An attempt at data cleaning for Hazelrig rainfall record

Some arbitrary choices here... might be better to set mis-typed values to NA?

Piping within the mutate here was a new discovery for me - genius!

```{r rain}
hr <- read_xls("Hazelrigg Rainfall 1966-.xls",
               range = "year!A1:BI367",
               col_types = c("numeric", "numeric", rep("text", 59))
) |>
  pivot_longer("1966":"2024", names_to = "year", values_to = "rainfall_mm") |>
  mutate(rainfall_mm = rainfall_mm |>
           #replace Trace|trace|tr|Tr with 0.01
           str_replace_all("[Tt]{1}.*\\b", "0.01") |>
           #replace anything starting with "a point"." with "0."
           # some ambiguity because could be that ".0" was typed instead of "0."
           str_replace_all("^\\.(.*)", "0.\\1") |>
           #remove trailing point symbol
           str_replace_all("(.*)\\.$", "\\1") |>
           #convert to numeric and round to 2 dp
           as.numeric() #|> round(digits = 2)
  ) |>
  arrange(year, Month, Date) |>
  clean_names()

```

Hourly data retrieved from data loggers, but note these are only last 2 years.

```{r, hourly}
# HAZELRIGG: Campbell Scientific Automatic Weather Stations
# 
# (A)	Main Hazelrigg meteorological enclosure, GR 493 578, c. 95m asl.
# (B)	New enclosure, GR 490 579, c.85m asl (just across the motorway from the N end of Campus).
# 
# Wind turbine is between the two sites at GR 492 578.
# 
# The data are all 10 minute averages (or totals) and the columns are:
#     
#     Station A:
#     
# E - Temperature (°C) (measured by temp/RH sensor in Stevenson Screen)
# F - Relative Humidity (%) in Stevenson Screen
# G - Solar irradiation: 10 min average (kW/m2)
# H - Solar irradiation: 10 min total (kJ/m2)
# I, J - Sunshine duration (minutes, seconds)
# K - Air temperature in Stevenson Screen (°C)
# L - Concrete temperature (°C)
# M - Grass temperature (°C)
# N, O, P, Q, R, S - Soil temperatures at 5, 10, 20, 30, 50, 100cm (°C)
# T, U, V, W - Sonic Anemometer (wind speed in 3 planes)
# Y - Windspeed at 10m on mast (m/s)
# Z - Wind direction at 10m on mast (degrees)
# AA - Rainfall 10 min total (mm)
# AB - Air Pressure (mbar)


log<-read.csv('loggers/CCSL006413_A_Ten_Min.dat', skip=1)
units<-log[1:2,]

# drop units and logger metadata
log<-log[-c(1:2),] %>% 
    clean_names()

# create hourly values
hour<-log %>% mutate(date = as.Date(str_split_fixed(timestamp, n=2, pattern = ' ')[,1]),
                     month = month(date),
                     year = year(date),
                     time = str_split_fixed(timestamp, n=2, pattern = ' ')[,2],
                     hour = str_split_fixed(time, n=3, pattern = '\\:')[,1],
                     .after = timestamp) %>%
    mutate(across(c(hour, p_temp_c_avg:bp_mbar),as.numeric)) %>% 
    group_by(date, month, year, hour) %>% 
    summarise(air_temp_c = mean(air_tc_avg, na.rm=TRUE),
              rel_humidity = mean(rh),
              solar_irradiation = sum(slr_k_j_tot, na.rm=TRUE),
              sunshine_mins = sum(sun_mins) + sum(sun_secs)/60,
              windspeed = mean(a100lk_ws_ms_s_wvt),
              wind_direction = mean(w200p_wd_d1_wvt),
              rainfall = sum(rain_mm_tot),
              air_pressure = mean(bp_mbar)
              )
```



